name: Generate README

on:
  schedule:
    - cron: '25 4 * * *'  # Runs daily at 10:00 AM IST (4:30 AM UTC)
  workflow_dispatch:  # Allows you to manually trigger the workflow

permissions:
  contents: write  # Allows the workflow to push changes to the repository

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython

      - name: Run script
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: python automator.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Automated README generation"
          git push https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/VisaganSP/dsa-training-problems-automater.git HEAD:main
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
